DROP TABLE attfile;
DROP SEQUENCE file_seq;

CREATE SEQUENCE file_seq NOCACHE;
CREATE TABLE attfile (
	fid NUMBER,
	bid NUMBER,
	fname NVARCHAR2(512) NOT NULL,
	path NVARCHAR2(1024) NOT NULL,
	url NVARCHAR2(1024) NOT NULL
);

ALTER TABLE attfile ADD CONSTRAINT attfile_fid_PK PRIMARY KEY(fid);
ALTER TABLE attfile ADD CONSTRAINT attfile_bid_FK FOREIGN KEY(bid) REFERENCES board(bid);